name: my-environment
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8
  - pandas
  - requests
  - plotly
  - ipywidgets
  - numpy
  - matplotlib
  - pillow
  - jupyterlab
  - pip
  - pip:
      - plotly
      - requests
